const fs=require('fs'),p='src/browser-runtime.html';let s=fs.readFileSync(p,'utf8');
function one(a,b){const n=s.split(a).length-1;if(n!==1)throw Error(n+' matches: '+a.slice(0,130));s=s.replace(a,b);}
const js=fs.readFileSync('.codex/mobile-interface.js','utf8'),css=fs.readFileSync('.codex/mobile-interface.css','utf8');
one('const CURRENT_GAME_BUILD=',js+'\nconst CURRENT_GAME_BUILD=');one('</head>','<style id="aegis-mobile-interface">\n'+css+'\n</style></head>');
one('width=device-width, initial-scale=1.0','width=device-width, initial-scale=1.0, viewport-fit=cover');
one('function AlienResponseCommand(){const initialGame=', 'function AlienResponseCommand(){const interfaceLayout=useAegisInterfaceLayout();const[mobileCommandOpen,setMobileCommandOpen]=useState(false);const initialGame=');
one('if(screen==="start"){return/*#__PURE__*/React.createElement("div",{className:', 'if(screen==="start"){return/*#__PURE__*/React.createElement("div",{"data-aegis-start-screen":"true",className:');
one('className:"relative overflow-hidden rounded-[2rem] border border-cyan-300/40 bg-slate-950/75 p-8', '"data-aegis-start-card":"true",className:"relative overflow-hidden rounded-[2rem] border border-cyan-300/40 bg-slate-950/75 p-8');
one('CURRENT_GAME_BUILD),/*#__PURE__*/React.createElement("div",{className:"mt-6 flex flex-wrap', 'CURRENT_GAME_BUILD),React.createElement(AegisInterfaceLayoutControl,null),/*#__PURE__*/React.createElement("div",{className:"mt-6 flex flex-wrap');
// Provide the same preference in the existing save/settings screen.
one('React.createElement(TacticalThreeIsoColorControl,{controlId:"menu-tactical-three-iso-color"})','React.createElement(AegisInterfaceLayoutControl,null),React.createElement(TacticalThreeIsoColorControl,{controlId:"menu-tactical-three-iso-color"})');
one('className:`min-h-screen bg-gradient-to-br from-slate-950 via-slate-950 to-slate-900 text-slate-100 ${darkMode?', '"data-aegis-command-root":"true","data-mobile-command-open":String(mobileCommandOpen),className:`min-h-screen bg-gradient-to-br from-slate-950 via-slate-950 to-slate-900 text-slate-100 ${darkMode?');
one('style:isTacticalView?undefined:commandBackgroundStyle(tab)},/*#__PURE__*/React.createElement(RangeSliderStyles,null),','style:isTacticalView?undefined:commandBackgroundStyle(tab)},interfaceLayout==="mobile"&&!isTacticalView&&React.createElement(AegisMobileCommandRails,{tabs,tab,onTab:id=>{setTab(id);setMobileCommandOpen(false);},onMenu:()=>openSaveMenuFrom("game"),onCommand:()=>{setHeaderMinimized(false);setMobileCommandOpen(value=>!value);},onIncidents:()=>setIncidentListOpen(true),onUfos:()=>setActiveUfoListOpen(true),running:geoscapeClockRunning,onPause:()=>setGeoscapeSpeed(geoscapeClockRunning?0:(geoscapeTickMinutes||1)),disabled:gameOver||Boolean(activeMission?.manual)}),/*#__PURE__*/React.createElement(RangeSliderStyles,null),');
one(',headerMinimized&&!isTacticalView&&/*#__PURE__*/React.createElement("div",{className:', ',headerMinimized&&!isTacticalView&&/*#__PURE__*/React.createElement("div",{"data-aegis-standard-header":"minimized",className:');
one('!headerMinimized&&!isTacticalView&&/*#__PURE__*/React.createElement("div",{className:', '!headerMinimized&&!isTacticalView&&/*#__PURE__*/React.createElement("div",{"data-aegis-standard-header":"expanded",className:');
one('const TacticalMiniHeader=()=>/*#__PURE__*/React.createElement("aside",{className:', 'const TacticalMiniHeader=()=>/*#__PURE__*/React.createElement("aside",{"data-aegis-tactical-mini-header":"true",className:');
one('backdrop-blur lg:w-60"},/*#__PURE__*/React.createElement("label",','backdrop-blur lg:w-60"},React.createElement("button",{className:"aegis-mobile-only aegis-mobile-drawer-close",onClick:()=>setMobileCommandOpen(false)},"Close command"),/*#__PURE__*/React.createElement("label",');
const start='function TacticalMission({mission,squad,tech,weaponUpgrades=normalizeWeaponUpgrades(),preparedDeployment=null,alienFieldBeaconKnowledge="unknown",onBeaconKnowledge=()=>{},onFinish,';
one(start,start.replace('onFinish,','onOpenMobileCommand=()=>{},onOpenMobileMenu=()=>{},onFinish,'));
one('const victoryMusicMissionRef=useRef(null);','const mobileLayout=useAegisInterfaceLayout()==="mobile";const[mobileDrawer,setMobileDrawer]=useState(null);const victoryMusicMissionRef=useRef(null);');
s=s.replaceAll('React.createElement(TacticalMissionStartup,{mission:activeMission,','React.createElement(TacticalMissionStartup,{onOpenMobileCommand:()=>setMobileCommandOpen(value=>!value),onOpenMobileMenu:()=>openSaveMenuFrom("game"),mission:activeMission,');
const root='return/*#__PURE__*/React.createElement("div",{className:`grid gap-1 ${aiMapPlayback?"":"lg:grid-cols-[minmax(0,1fr)_320px]"}`},';
const rails=`return/*#__PURE__*/React.createElement("div",{"data-aegis-tactical-layout":"true","data-mobile-drawer":mobileDrawer||"",className:\`grid gap-1 \${aiMapPlayback?"":"lg:grid-cols-[minmax(0,1fr)_320px]"}\`},
mobileLayout&&React.createElement(AegisMobileRail,{side:"left",label:"Tactical navigation"},
  React.createElement("div",{className:"aegis-mobile-unit"},React.createElement("b",null,tacticalStatusHudUnit?.name||selectedUnit?.name||"AEGIS"),"Round ",tacticalRound),
  aegisMobileButton("Command",onOpenMobileCommand),aegisMobileButton("Menu / Save",onOpenMobileMenu),
  aegisMobileButton("Previous",()=>selectSoldier(-1),{ariaLabel:"Previous soldier"}),aegisMobileButton("Next",()=>selectSoldier(1),{ariaLabel:"Next soldier"}),
  aegisMobileButton("Fit map",()=>setZoomIndex(TACTICAL_ZOOM_LEVELS.findIndex(level=>level.fitMap))),
  aegisMobileButton("Zoom +",()=>setZoomIndex(index=>index===5?2:Math.min(4,index+1))),aegisMobileButton("Zoom −",()=>setZoomIndex(index=>index===5?1:Math.max(0,index-1))),
  aegisMobileButton("Orders",openFireTeamCommandMap),
  aiMapPlayback&&aegisMobileButton("FPV",toggleAiFirstPersonObserver,{active:aiFirstPersonView}),aiMapPlayback&&aegisMobileButton("TPV",toggleAiThirdPersonObserver,{active:aiThirdPersonView})),
mobileLayout&&React.createElement(AegisMobileRail,{side:"right",label:"Tactical actions"},
  React.createElement("div",{className:"aegis-mobile-unit","aria-live":"polite"},"HP ",tacticalStatusHudUnit?.hp??selectedUnit?.hp??"—",React.createElement("br"),"TU ",tacticalStatusHudUnit?.tu??selectedUnit?.tu??"—"),
  !aiMapPlayback&&aegisMobileButton("Move",()=>setTargetingMode("move"),{active:targetingMode==="move",disabled:turn!=="human"||!selectedUnit||Boolean(movingUnit)||battleResolved}),
  !aiMapPlayback&&aegisMobileButton("Fire",()=>setTargetingMode("fire"),{active:targetingMode==="fire",disabled:turn!=="human"||!selectedUnit||Boolean(movingUnit)||battleResolved}),
  !aiMapPlayback&&aegisMobileButton(selectedUnit?.kneeling?"Stand":"Kneel",toggleSelectedKneel,{disabled:turn!=="human"||!selectedUnit||Boolean(movingUnit)||battleResolved}),
  !aiMapPlayback&&aegisMobileButton("Gear",()=>{setShowTacticalInventory(true);setMobileDrawer(value=>value==="controls"?null:"controls");},{disabled:!selectedUnit,active:mobileDrawer==="controls"}),
  aegisMobileButton(mobileDrawer?"Close panel":"More",()=>setMobileDrawer(value=>value?null:"more"),{active:Boolean(mobileDrawer)}),
  !aiMapPlayback&&!battleResolved&&aegisMobileButton("AI Command",()=>handOffToSimulationAi("map"),{disabled:turn!=="human"||Boolean(movingUnit)||Boolean(aiHandoffLoading)}),
  !aiMapPlayback&&!battleResolved&&aegisMobileButton("End turn",endTurn,{primary:true,disabled:turn!=="human"||Boolean(movingUnit)}),
  aiMapPlayback&&aegisMobileButton(commandMapPaused?"Resume":"Pause",commandMapPaused?resumeFireTeamCommandMapAction:pauseFireTeamCommandMapAction,{primary:true,disabled:commandMapPauseRequested}),
  aiMapPlayback&&aegisMobileButton("Take back",takeBackAiCommand),
  battleResolved&&aegisMobileButton("Finish mission",()=>aiPlayback?finishAiPlayback():finish(battleOutcome==="victory"),{primary:true,disabled:aiFrameAnimating})),`;
one(root,rails);
one('React.createElement("div",{className:`min-h-0 rounded-3xl border shadow-sm ${aiMapPlayback?', 'React.createElement("div",{"data-aegis-battle-surface":"true",className:`min-h-0 rounded-3xl border shadow-sm ${aiMapPlayback?');
one('React.createElement("div",{className:"mb-1 flex flex-col gap-1 lg:flex-row lg:items-center lg:justify-between"},','React.createElement("div",{"data-aegis-tactical-toolbar":"true",className:"mb-1 flex flex-col gap-1 lg:flex-row lg:items-center lg:justify-between"},mobileLayout&&React.createElement("button",{className:"aegis-mobile-drawer-close",onClick:()=>setMobileDrawer(null)},"Close controls"),mobileLayout&&React.createElement(TacticalReinforcementSourceStatus,{mission,covers,units,knowledge:alienFieldBeaconKnowledge,selectedUnit,turn,onInspect:inspectCrashedUfoBay}),mobileLayout&&React.createElement(TacticalEscortSupportDoctrineControl,{value:escortSupportDoctrine,onChange:changeEscortSupportDoctrine,onReview:openEscortSupportAssignmentBoard,reviewDisabled:aiEscortSupportTeams.length===0||Boolean(movingUnit)||aiFrameAnimating,compact:true,controlId:"mobile-escort-support-doctrine"}),');
const doctrine='/*#__PURE__*/React.createElement(TacticalEscortSupportDoctrineControl,{value:escortSupportDoctrine,onChange:changeEscortSupportDoctrine,onReview:openEscortSupportAssignmentBoard,reviewDisabled:aiEscortSupportTeams.length===0||Boolean(movingUnit)||aiFrameAnimating,compact:true,controlId:"battle-escort-support-doctrine"})';one(doctrine,'!mobileLayout&&'+doctrine);
const status='/*#__PURE__*/React.createElement(TacticalReinforcementSourceStatus,{mission,covers,units,knowledge:alienFieldBeaconKnowledge,selectedUnit,turn,onInspect:inspectCrashedUfoBay})';one(status,'!mobileLayout&&'+status);
one('className:"mb-1 flex flex-col gap-2 rounded-2xl border border-violet-400/40 bg-slate-950/90 p-2 text-xs text-violet-100 shadow-sm md:flex-row md:items-center md:justify-between"','"data-aegis-ai-playback-banner":"true",className:"mb-1 flex flex-col gap-2 rounded-2xl border border-violet-400/40 bg-slate-950/90 p-2 text-xs text-violet-100 shadow-sm md:flex-row md:items-center md:justify-between"');
one('className:`relative rounded-2xl border border-cyan-900/40 bg-cyan-950 p-2 shadow-inner','"data-aegis-battle-viewport":"true",className:`relative rounded-2xl border border-cyan-900/40 bg-cyan-950 p-2 shadow-inner');
one('tacticalViewMode==="3d"&&/*#__PURE__*/React.createElement("div",{className:"relative min-h-[520px]"}', 'tacticalViewMode==="3d"&&/*#__PURE__*/React.createElement("div",{"data-aegis-three-wrap":"true",className:"relative min-h-[520px]"}');
one('!aiMapPlayback&&/*#__PURE__*/React.createElement("div",{className:"max-h-[calc(100vh-1rem)] overflow-auto rounded-3xl border p-3 shadow-sm"},', '!aiMapPlayback&&/*#__PURE__*/React.createElement("div",{"data-aegis-tactical-controls":"true",className:"max-h-[calc(100vh-1rem)] overflow-auto rounded-3xl border p-3 shadow-sm"},mobileLayout&&React.createElement("button",{className:"aegis-mobile-drawer-close",onClick:()=>setMobileDrawer(null)},"Close equipment"),');
one('const tacticalAvailableWidth=aiMapPlayback?','const tacticalAvailableWidth=mobileLayout?"calc(100vw - 176px)":aiMapPlayback?');
one('const tacticalAvailableHeight=`calc(100vh - ${tacticalPanelOffset}px)`','const tacticalAvailableHeight=mobileLayout?"100dvh":`calc(100vh - ${tacticalPanelOffset}px)`');
// Keep desktop camera limits; use the actual mobile canvas aspect and resolution.
one('const width=Math.max(640,runtime.mount.clientWidth||runtime.width||960);const height=Math.max(420,runtime.mount.clientHeight||runtime.height||640);runtime.width=width;', 'const{width,height}=aegisTacticalViewportDimensions(runtime.mount,runtime);runtime.width=width;');
s=s.replaceAll('mount.innerHTML="";const width=Math.max(640,mount.clientWidth||960);const height=Math.max(420,mount.clientHeight||640);const scene=', 'mount.innerHTML="";const{width,height}=aegisTacticalViewportDimensions(mount);const scene=');
s=s.replaceAll('const aspect=Math.max(0.75,(Number(width)||960)/safeHeight);','const aspect=Math.max(AEGIS_INTERFACE_LAYOUT==="mobile"?0.1:0.75,(Number(width)||960)/safeHeight);');
one('if(mode!=="auto")return mode;return Number(hints.cores)', 'if(mode!=="auto")return mode;if(AEGIS_INTERFACE_LAYOUT==="mobile")return"performance";return Number(hints.cores)');
one('window.addEventListener("resize",runtime.onResize);if(typeof window', 'window.addEventListener("resize",runtime.onResize);if(typeof ResizeObserver!=="undefined"){runtime.viewportObserver=new ResizeObserver(runtime.onResize);runtime.viewportObserver.observe(mount);}if(typeof window');
one('function tacticalThreePersistentDisposeRuntime(runtime){','function tacticalThreePersistentDisposeRuntime(runtime){\n  runtime?.viewportObserver?.disconnect();');
fs.writeFileSync(p,s);
