const AEGIS_PWA_CACHE = "aegis-v0.26.09.22.0008_FENCE_ENCLOSURES_AND_ACCESS_GAPS_PATCH";
const AEGIS_RUNTIME_CACHE = "aegis-runtime-v0.26.09.22.0008_FENCE_ENCLOSURES_AND_ACCESS_GAPS_PATCH";
const AEGIS_LAUNCH_CACHE = "aegis-launch-shell-v19-fence-enclosures";
const AEGIS_BUILD = AEGIS_PWA_CACHE.slice("aegis-".length);
const AEGIS_SHELL_URL = new URL("./index.html", self.registration.scope).href;
const AEGIS_RELEASE_URL = new URL("./release-metadata.json", self.registration.scope).href;
const AEGIS_PROP_LIBRARY_URL = new URL("./assets/data/aegis-prop-library.js", self.registration.scope).href;
const AEGIS_PLACEMENT_RULES_URL = new URL("./assets/data/aegis-prop-placement-rules.js", self.registration.scope).href;
const AEGIS_PLACEMENT_OVERRIDES_URL = new URL("./assets/data/aegis-prop-placement-overrides.js", self.registration.scope).href;
const AEGIS_CONTEXT_RUNTIME_URL = new URL("./assets/runtime/aegis-contextual-prop-placement-runtime.js", self.registration.scope).href;
const AEGIS_TOOLS_EDITOR_RUNTIME_URL = new URL("./assets/runtime/aegis-tools-editor-launcher-runtime.js", self.registration.scope).href;
const AEGIS_TOOL_NAV_URLS = new Set([
  new URL("./AEGIS_TV.html", self.registration.scope).href,
  new URL("./AEGIS_Phone_Controller.html", self.registration.scope).href,
  new URL("./AEGIS_Building_Layout_Editor_CURRENT.html", self.registration.scope).href,
  new URL("./AEGIS_Tools_Editors.html", self.registration.scope).href,
  new URL("./AEGIS_Prop_Editor_CURRENT.html", self.registration.scope).href,
  new URL("./AEGIS_Prop_Editor_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html", self.registration.scope).href,
  new URL("./AEGIS_Prop_Runtime_Test_Gallery_CURRENT.html", self.registration.scope).href,
  new URL("./AEGIS_Prop_Runtime_Test_Gallery_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html", self.registration.scope).href
]);
const AEGIS_BOOT_PROBE_TIMEOUT_MS = 1800;
const AEGIS_SMALL_SHELL = [
  "./AEGIS_TV.html",
  "./AEGIS_Phone_Controller.html",
  "./assets/vendor/peerjs-1.5.5.min.js",
  "./assets/vendor/qrcode-generator-2.0.4.js",
  "./assets/runtime/aegis-tv-protocol.js",
  "./assets/runtime/aegis-tv-input.js",
  "./assets/runtime/aegis-tv-host.js",
  "./assets/runtime/aegis-tv-runtime.js",
  "./assets/runtime/aegis-tv-phone.js",
  "./AEGIS_Building_Layout_Editor_CURRENT.html",
  "./assets/runtime/aegis-building-layouts.js",
  "./assets/runtime/aegis-building-editor-runtime.js",
  "./assets/runtime/aegis-building-editor-ui.js",
  "./manifest.webmanifest",
  "./assets/icons/aegis-192.png",
  "./assets/icons/aegis-512.png",
  "./release-metadata.json",
  "./AEGIS_Tools_Editors.html",
  "./assets/data/aegis-prop-library.js",
  "./assets/data/aegis-prop-placement-rules.js",
  "./AEGIS_Prop_Editor_CURRENT.html",
  "./AEGIS_Prop_Editor_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html",
  "./AEGIS_Prop_Runtime_Test_Gallery_CURRENT.html",
  "./AEGIS_Prop_Runtime_Test_Gallery_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html",
  "./assets/runtime/aegis-contextual-prop-placement-runtime.js",
  "./assets/runtime/aegis-tools-editor-launcher-runtime.js"
];
function isCacheableResponse(response){return Boolean(response&&response.ok&&(response.type==="basic"||response.type==="default"));}
async function cacheFreshSmallShell(cache){for(const relative of AEGIS_SMALL_SHELL){const url=new URL(relative,self.registration.scope).href;const request=new Request(url,{cache:"reload",credentials:"same-origin"});const response=await fetch(request);if(!isCacheableResponse(response))throw new Error(`Unable to cache fresh AEGIS shell resource: ${relative}`);await cache.put(url,response.clone());}}
async function fetchWithTimeout(request,options={},timeoutMs=AEGIS_BOOT_PROBE_TIMEOUT_MS){const controller=typeof AbortController==="function"?new AbortController():null;const timer=controller?setTimeout(()=>controller.abort(),Math.max(250,Number(timeoutMs)||0)):0;try{return await fetch(request,controller?{...options,signal:controller.signal}:options);}finally{if(timer)clearTimeout(timer);}}
async function probePublishedBuild(){const url=new URL(AEGIS_RELEASE_URL);url.searchParams.set("aegis_probe",`${AEGIS_BUILD}-${Date.now()}`);const response=await fetchWithTimeout(new Request(url.href,{cache:"no-store",credentials:"same-origin"}),{},AEGIS_BOOT_PROBE_TIMEOUT_MS);if(!isCacheableResponse(response))return null;const metadata=await response.json().catch(()=>null);return typeof metadata?.build==="string"&&metadata.build?metadata.build:null;}
async function fetchPublishedShell(build=AEGIS_BUILD){const url=new URL(AEGIS_SHELL_URL);url.searchParams.set("aegis_build",String(build||AEGIS_BUILD));return fetch(new Request(url.href,{cache:"no-store",credentials:"same-origin"}));}
function toolsLauncherTag(){return `<script data-aegis-tools-editor-runtime="${AEGIS_BUILD}" src="${AEGIS_TOOLS_EDITOR_RUNTIME_URL}"></script>`;}
const AEGIS_NATIVE_TOOLS_BUTTON_MARKER='data-aegis-open-tools-editors';
const AEGIS_NATIVE_TOOLS_ANCHOR='/*#__PURE__*/React.createElement("button",{onClick:()=>setSfxLibraryOpen(true),"data-aegis-open-sfx-library":"true",className:"rounded-2xl border border-cyan-400/50 bg-cyan-950/45 px-4 py-2 text-sm font-black text-cyan-100 shadow-sm"},"Enhanced SFX Library"),';
const AEGIS_NATIVE_TOOLS_BUTTON='/*#__PURE__*/React.createElement("button",{type:"button","data-aegis-open-tools-editors":"true",title:"Open Project Aegis development tools.",onClick:()=>{const u=new URL("./AEGIS_Tools_Editors.html",document.baseURI).href;let opened=null;try{opened=window.open(u,"aegis-tools-editors");}catch{}if(!opened){window.alert("The browser blocked the tools window. Allow pop-ups for Project Aegis, then try again. Your campaign remains open.");}},className:"rounded-2xl border border-violet-300/70 bg-violet-950/55 px-4 py-2 text-sm font-black text-violet-100 shadow-sm"},"Tools / Editors"),';
function utf8Bytes(text){return new TextEncoder().encode(String(text??""));}
function base64ToUtf8(base64){const binary=atob(String(base64||"").replace(/\s+/g,""));const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new TextDecoder().decode(bytes);}
function utf8ToBase64(text){const bytes=utf8Bytes(text);let binary="";const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+chunk)));return btoa(binary);}
async function sha256Hex(bytes){const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,"0")).join("");}
function patchNativeToolsButton(runtimeText){if(runtimeText.includes(AEGIS_NATIVE_TOOLS_BUTTON_MARKER))return{runtimeText,changed:false,reason:"already-patched"};if(!runtimeText.includes(AEGIS_NATIVE_TOOLS_ANCHOR))return{runtimeText,changed:false,reason:"anchor-missing"};return{runtimeText:runtimeText.replace(AEGIS_NATIVE_TOOLS_ANCHOR,AEGIS_NATIVE_TOOLS_ANCHOR+AEGIS_NATIVE_TOOLS_BUTTON),changed:true,reason:"patched"};}
async function patchEmbeddedRuntimePayload(shellText){const payloadPattern=/<script\b([^>]*\bid=["']aegis-runtime-payload["'][^>]*)>([\s\S]*?)<\/script>/i;const match=payloadPattern.exec(shellText);if(!match)return{shellText,changed:false,reason:"payload-missing"};let runtimeText;try{runtimeText=base64ToUtf8(match[2]);}catch(error){return{shellText,changed:false,reason:"payload-decode-failed"};}const patched=patchNativeToolsButton(runtimeText);if(!patched.changed&&patched.reason!=="already-patched")return{shellText,changed:false,reason:patched.reason};if(!patched.changed)return{shellText,changed:false,reason:patched.reason};const bytes=utf8Bytes(patched.runtimeText);const hash=await sha256Hex(bytes);const encoded=utf8ToBase64(patched.runtimeText);let attrs=match[1];if(/\bdata-source-bytes=["'][^"']*["']/i.test(attrs))attrs=attrs.replace(/\bdata-source-bytes=["'][^"']*["']/i,`data-source-bytes="${bytes.length}"`);else attrs+=` data-source-bytes="${bytes.length}"`;if(/\bdata-sha256=["'][^"']*["']/i.test(attrs))attrs=attrs.replace(/\bdata-sha256=["'][^"']*["']/i,`data-sha256="${hash}"`);else attrs+=` data-sha256="${hash}"`;if(/\bdata-aegis-native-tools-build=["'][^"']*["']/i.test(attrs))attrs=attrs.replace(/\bdata-aegis-native-tools-build=["'][^"']*["']/i,`data-aegis-native-tools-build="${AEGIS_BUILD}"`);else attrs+=` data-aegis-native-tools-build="${AEGIS_BUILD}"`;const replacement=`<script${attrs}>${encoded}</script>`;return{shellText:shellText.slice(0,match.index)+replacement+shellText.slice(match.index+match[0].length),changed:true,reason:"patched",runtimeBytes:bytes.length,sha256:hash};}
async function transformLaunchShell(response){if(!isCacheableResponse(response))return response;const headers=new Headers(response.headers);const type=String(headers.get("content-type")||"");if(type&&!type.includes("text/html"))return response;let text=await response.text();const nativePatch=await patchEmbeddedRuntimePayload(text);text=nativePatch.shellText;if(!text.includes('data-aegis-tools-editor-runtime')){const tag=toolsLauncherTag();if(/<\/body\s*>/i.test(text))text=text.replace(/<\/body\s*>/i,`${tag}</body>`);else if(/<\/html\s*>/i.test(text))text=text.replace(/<\/html\s*>/i,`${tag}</html>`);else text+=tag;}headers.set("content-type","text/html; charset=utf-8");headers.delete("content-length");headers.set("x-aegis-tools-editor-shell",AEGIS_BUILD);headers.set("x-aegis-native-tools-editor-runtime",nativePatch.reason);if(nativePatch.sha256)headers.set("x-aegis-native-runtime-sha256",nativePatch.sha256);return new Response(text,{status:response.status,statusText:response.statusText,headers});}
async function cacheLaunchShell(response){if(!isCacheableResponse(response))return false;const cache=await caches.open(AEGIS_LAUNCH_CACHE);await cache.put(AEGIS_SHELL_URL,response.clone());return true;}
async function cleanupOldVersionedCaches(){const keep=new Set([AEGIS_PWA_CACHE,AEGIS_RUNTIME_CACHE,AEGIS_LAUNCH_CACHE]);const keys=await caches.keys();await Promise.all(keys.filter(key=>(key.startsWith("aegis-")||key.startsWith("aegis-runtime-"))&&!keep.has(key)).map(key=>caches.delete(key)));}
async function fetchPlacementScript(url,required=false){try{const cached=await caches.match(url);const response=cached||await fetch(new Request(url,{cache:"no-cache",credentials:"same-origin"}));if(!isCacheableResponse(response))return required?null:"";return await response.text();}catch{return required?null:"";}}
async function transformedPropLibraryResponse(request){let base=await caches.match(request);if(!base){base=await fetch(request,{cache:"no-cache"});if(isCacheableResponse(base))(await caches.open(AEGIS_RUNTIME_CACHE)).put(request,base.clone()).catch(()=>{});}if(!isCacheableResponse(base))return base;const baseText=await base.text();const rulesText=await fetchPlacementScript(AEGIS_PLACEMENT_RULES_URL,true);if(rulesText===null)return new Response(baseText,{status:base.status,statusText:base.statusText,headers:base.headers});const overrideText=await fetchPlacementScript(AEGIS_PLACEMENT_OVERRIDES_URL,false);const loader=`\n;(()=>{const load=(src,flag,dataKey)=>{if(window[flag])return;window[flag]=true;const s=document.createElement('script');s.src=src;s.dataset[dataKey]='true';s.onload=()=>{window[flag]=false};s.onerror=()=>{window[flag]=false};document.head.appendChild(s);};load(${JSON.stringify(AEGIS_CONTEXT_RUNTIME_URL)},'__AEGIS_CONTEXTUAL_PROP_RUNTIME_LOADING','aegisContextualPropRuntime');load(${JSON.stringify(AEGIS_TOOLS_EDITOR_RUNTIME_URL)},'__AEGIS_TOOLS_EDITOR_RUNTIME_LOADING','aegisToolsEditorRuntime');})();\n`;const headers=new Headers(base.headers);headers.set("content-type","application/javascript; charset=utf-8");headers.delete("content-length");return new Response(`${baseText}\n${rulesText}\n${overrideText||""}${loader}`,{status:200,headers});}
self.addEventListener("install",event=>{event.waitUntil((async()=>{const cache=await caches.open(AEGIS_PWA_CACHE);await cacheFreshSmallShell(cache);await self.skipWaiting();})());});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{await cleanupOldVersionedCaches();await self.clients.claim();})());});
self.addEventListener("message",event=>{if(event?.data?.type==="AEGIS_SKIP_WAITING")self.skipWaiting();});
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin||request.headers.has("range"))return;if(url.href===AEGIS_PROP_LIBRARY_URL){event.respondWith(transformedPropLibraryResponse(request));return;}if(request.mode==="navigate"&&AEGIS_TOOL_NAV_URLS.has(url.origin+url.pathname)){event.respondWith((async()=>{const toolCacheKey=url.origin+url.pathname;const cached=await caches.match(toolCacheKey);if(cached)return cached;const fresh=await fetch(request,{cache:"no-cache"});if(isCacheableResponse(fresh))(await caches.open(AEGIS_RUNTIME_CACHE)).put(toolCacheKey,fresh.clone()).catch(()=>{});return fresh;})());return;}if(request.mode==="navigate"){const shellUrl=new URL(AEGIS_SHELL_URL),rootUrl=new URL("./",shellUrl);if(url.pathname!==shellUrl.pathname&&url.pathname!==rootUrl.pathname)return;event.respondWith((async()=>{const launchCache=await caches.open(AEGIS_LAUNCH_CACHE),cachedLaunch=await launchCache.match(AEGIS_SHELL_URL);let publishedBuild=null;try{publishedBuild=await probePublishedBuild();}catch{}if(publishedBuild&&publishedBuild!==AEGIS_BUILD){try{const fresh=await transformLaunchShell(await fetchPublishedShell(publishedBuild));if(isCacheableResponse(fresh)){event.waitUntil(cacheLaunchShell(fresh.clone()).then(cleanupOldVersionedCaches).catch(()=>{}));return fresh;}}catch{}}if(cachedLaunch)return cachedLaunch;try{const fresh=await transformLaunchShell(await fetchPublishedShell(publishedBuild||AEGIS_BUILD));if(isCacheableResponse(fresh)){event.waitUntil(cacheLaunchShell(fresh.clone()).then(cleanupOldVersionedCaches).catch(()=>{}));return fresh;}}catch{}const keys=await caches.keys();for(const key of keys.reverse()){if(!key.startsWith("aegis-")||key===AEGIS_RUNTIME_CACHE||key===AEGIS_LAUNCH_CACHE)continue;try{const fallback=await(await caches.open(key)).match(AEGIS_SHELL_URL);if(fallback)return await transformLaunchShell(fallback);}catch{}}return Response.error();})());return;}event.respondWith((async()=>{const cached=await caches.match(request);if(cached){event.waitUntil(fetch(request,{cache:"no-cache"}).then(async fresh=>{if(isCacheableResponse(fresh))(await caches.open(AEGIS_RUNTIME_CACHE)).put(request,fresh.clone()).catch(()=>{});}).catch(()=>{}));return cached;}const fresh=await fetch(request,{cache:"no-cache"});if(isCacheableResponse(fresh))(await caches.open(AEGIS_RUNTIME_CACHE)).put(request,fresh.clone()).catch(()=>{});return fresh;})());});
