const AEGIS_PWA_CACHE = "aegis-v0.26.09.18.2115_IN_GAME_TOOLS_EDITOR_RENDERED_RUNTIME_HOTFIX";
const AEGIS_RUNTIME_CACHE = "aegis-runtime-v0.26.09.18.2115_IN_GAME_TOOLS_EDITOR_RENDERED_RUNTIME_HOTFIX";
const AEGIS_LAUNCH_CACHE = "aegis-launch-shell-v3-tools-editor-hotfix";
const AEGIS_BUILD = AEGIS_PWA_CACHE.slice("aegis-".length);
const AEGIS_SHELL_URL = new URL("./index.html", self.registration.scope).href;
const AEGIS_RELEASE_URL = new URL("./release-metadata.json", self.registration.scope).href;
const AEGIS_PROP_LIBRARY_URL = new URL("./assets/data/aegis-prop-library.js", self.registration.scope).href;
const AEGIS_PLACEMENT_RULES_URL = new URL("./assets/data/aegis-prop-placement-rules.js", self.registration.scope).href;
const AEGIS_PLACEMENT_OVERRIDES_URL = new URL("./assets/data/aegis-prop-placement-overrides.js", self.registration.scope).href;
const AEGIS_CONTEXT_RUNTIME_URL = new URL("./assets/runtime/aegis-contextual-prop-placement-runtime.js", self.registration.scope).href;
const AEGIS_TOOLS_EDITOR_RUNTIME_URL = new URL("./assets/runtime/aegis-tools-editor-launcher-runtime.js", self.registration.scope).href;
const AEGIS_TOOL_NAV_URLS = new Set([
  new URL("./AEGIS_Prop_Editor_CURRENT.html", self.registration.scope).href,
  new URL("./AEGIS_Prop_Editor_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html", self.registration.scope).href,
  new URL("./AEGIS_Prop_Runtime_Test_Gallery_CURRENT.html", self.registration.scope).href,
  new URL("./AEGIS_Prop_Runtime_Test_Gallery_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html", self.registration.scope).href
]);
const AEGIS_BOOT_PROBE_TIMEOUT_MS = 1800;
const AEGIS_SMALL_SHELL = [
  "./manifest.webmanifest",
  "./assets/icons/aegis-192.png",
  "./assets/icons/aegis-512.png",
  "./release-metadata.json",
  "./assets/data/aegis-prop-library.js",
  "./assets/data/aegis-prop-placement-rules.js",
  "./AEGIS_Prop_Editor_CURRENT.html",
  "./AEGIS_Prop_Editor_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html",
  "./AEGIS_Prop_Runtime_Test_Gallery_CURRENT.html",
  "./AEGIS_Prop_Runtime_Test_Gallery_v0.26.09.18.2051_IN_GAME_TOOLS_AND_PROP_EDITOR_ACCESS_PATCH.html",
  "./assets/runtime/aegis-contextual-prop-placement-runtime.js",
  "./assets/runtime/aegis-tools-editor-launcher-runtime.js"
];
function isCacheableResponse(response){return Boolean(response&&response.ok&&(response.type==="basic"||response.type==="default"));}
async function cacheFreshSmallShell(cache){for(const relative of AEGIS_SMALL_SHELL){const url=new URL(relative,self.registration.scope).href;const request=new Request(url,{cache:"reload",credentials:"same-origin"});const response=await fetch(request);if(!isCacheableResponse(response))throw new Error(`Unable to cache fresh AEGIS shell resource: ${relative}`);await cache.put(url,response.clone());}}
async function fetchWithTimeout(request,options={},timeoutMs=AEGIS_BOOT_PROBE_TIMEOUT_MS){const controller=typeof AbortController==="function"?new AbortController():null;const timer=controller?setTimeout(()=>controller.abort(),Math.max(250,Number(timeoutMs)||0)):0;try{return await fetch(request,controller?{...options,signal:controller.signal}:options);}finally{if(timer)clearTimeout(timer);}}
async function probePublishedBuild(){const url=new URL(AEGIS_RELEASE_URL);url.searchParams.set("aegis_probe",`${AEGIS_BUILD}-${Date.now()}`);const response=await fetchWithTimeout(new Request(url.href,{cache:"no-store",credentials:"same-origin"}),{},AEGIS_BOOT_PROBE_TIMEOUT_MS);if(!isCacheableResponse(response))return null;const metadata=await response.json().catch(()=>null);return typeof metadata?.build==="string"&&metadata.build?metadata.build:null;}
async function fetchPublishedShell(build=AEGIS_BUILD){const url=new URL(AEGIS_SHELL_URL);url.searchParams.set("aegis_build",String(build||AEGIS_BUILD));return fetch(new Request(url.href,{cache:"no-store",credentials:"same-origin"}));}
function toolsLauncherTag(){return `<script data-aegis-tools-editor-runtime="${AEGIS_BUILD}" src="${AEGIS_TOOLS_EDITOR_RUNTIME_URL}"></script>`;}
async function transformLaunchShell(response){if(!isCacheableResponse(response))return response;const headers=new Headers(response.headers);const type=String(headers.get("content-type")||"");if(type&&!type.includes("text/html"))return response;let text=await response.text();if(!text.includes('data-aegis-tools-editor-runtime')){const tag=toolsLauncherTag();if(/<\/body\s*>/i.test(text))text=text.replace(/<\/body\s*>/i,`${tag}</body>`);else if(/<\/html\s*>/i.test(text))text=text.replace(/<\/html\s*>/i,`${tag}</html>`);else text+=tag;}headers.set("content-type","text/html; charset=utf-8");headers.delete("content-length");headers.set("x-aegis-tools-editor-shell",AEGIS_BUILD);return new Response(text,{status:response.status,statusText:response.statusText,headers});}
async function cacheLaunchShell(response){if(!isCacheableResponse(response))return false;const cache=await caches.open(AEGIS_LAUNCH_CACHE);await cache.put(AEGIS_SHELL_URL,response.clone());return true;}
async function cleanupOldVersionedCaches(){const keep=new Set([AEGIS_PWA_CACHE,AEGIS_RUNTIME_CACHE,AEGIS_LAUNCH_CACHE]);const keys=await caches.keys();await Promise.all(keys.filter(key=>(key.startsWith("aegis-")||key.startsWith("aegis-runtime-"))&&!keep.has(key)).map(key=>caches.delete(key)));}
async function fetchPlacementScript(url,required=false){try{const cached=await caches.match(url);const response=cached||await fetch(new Request(url,{cache:"no-cache",credentials:"same-origin"}));if(!isCacheableResponse(response))return required?null:"";return await response.text();}catch{return required?null:"";}}
async function transformedPropLibraryResponse(request){let base=await caches.match(request);if(!base){base=await fetch(request,{cache:"no-cache"});if(isCacheableResponse(base))(await caches.open(AEGIS_RUNTIME_CACHE)).put(request,base.clone()).catch(()=>{});}if(!isCacheableResponse(base))return base;const baseText=await base.text();const rulesText=await fetchPlacementScript(AEGIS_PLACEMENT_RULES_URL,true);if(rulesText===null)return new Response(baseText,{status:base.status,statusText:base.statusText,headers:base.headers});const overrideText=await fetchPlacementScript(AEGIS_PLACEMENT_OVERRIDES_URL,false);const loader=`\n;(()=>{const load=(src,flag,dataKey)=>{if(window[flag])return;window[flag]=true;const s=document.createElement('script');s.src=src;s.dataset[dataKey]='true';s.onload=()=>{window[flag]=false};s.onerror=()=>{window[flag]=false};document.head.appendChild(s);};load(${JSON.stringify(AEGIS_CONTEXT_RUNTIME_URL)},'__AEGIS_CONTEXTUAL_PROP_RUNTIME_LOADING','aegisContextualPropRuntime');load(${JSON.stringify(AEGIS_TOOLS_EDITOR_RUNTIME_URL)},'__AEGIS_TOOLS_EDITOR_RUNTIME_LOADING','aegisToolsEditorRuntime');})();\n`;const headers=new Headers(base.headers);headers.set("content-type","application/javascript; charset=utf-8");headers.delete("content-length");return new Response(`${baseText}\n${rulesText}\n${overrideText||""}${loader}`,{status:200,headers});}
self.addEventListener("install",event=>{event.waitUntil((async()=>{const cache=await caches.open(AEGIS_PWA_CACHE);await cacheFreshSmallShell(cache);await self.skipWaiting();})());});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{await cleanupOldVersionedCaches();await self.clients.claim();})());});
self.addEventListener("message",event=>{if(event?.data?.type==="AEGIS_SKIP_WAITING")self.skipWaiting();});
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin||request.headers.has("range"))return;if(url.href===AEGIS_PROP_LIBRARY_URL){event.respondWith(transformedPropLibraryResponse(request));return;}if(request.mode==="navigate"&&AEGIS_TOOL_NAV_URLS.has(url.href)){event.respondWith((async()=>{const cached=await caches.match(request);if(cached)return cached;const fresh=await fetch(request,{cache:"no-cache"});if(isCacheableResponse(fresh))(await caches.open(AEGIS_RUNTIME_CACHE)).put(request,fresh.clone()).catch(()=>{});return fresh;})());return;}if(request.mode==="navigate"){const shellUrl=new URL(AEGIS_SHELL_URL),rootUrl=new URL("./",shellUrl);if(url.pathname!==shellUrl.pathname&&url.pathname!==rootUrl.pathname)return;event.respondWith((async()=>{const launchCache=await caches.open(AEGIS_LAUNCH_CACHE),cachedLaunch=await launchCache.match(AEGIS_SHELL_URL);let publishedBuild=null;try{publishedBuild=await probePublishedBuild();}catch{}if(publishedBuild&&publishedBuild!==AEGIS_BUILD){try{const fresh=await transformLaunchShell(await fetchPublishedShell(publishedBuild));if(isCacheableResponse(fresh)){event.waitUntil(cacheLaunchShell(fresh.clone()).then(cleanupOldVersionedCaches).catch(()=>{}));return fresh;}}catch{}}if(cachedLaunch)return cachedLaunch;try{const fresh=await transformLaunchShell(await fetchPublishedShell(publishedBuild||AEGIS_BUILD));if(isCacheableResponse(fresh)){event.waitUntil(cacheLaunchShell(fresh.clone()).then(cleanupOldVersionedCaches).catch(()=>{}));return fresh;}}catch{}const keys=await caches.keys();for(const key of keys.reverse()){if(!key.startsWith("aegis-")||key===AEGIS_RUNTIME_CACHE||key===AEGIS_LAUNCH_CACHE)continue;try{const fallback=await(await caches.open(key)).match(AEGIS_SHELL_URL);if(fallback)return await transformLaunchShell(fallback);}catch{}}return Response.error();})());return;}event.respondWith((async()=>{const cached=await caches.match(request);if(cached){event.waitUntil(fetch(request,{cache:"no-cache"}).then(async fresh=>{if(isCacheableResponse(fresh))(await caches.open(AEGIS_RUNTIME_CACHE)).put(request,fresh.clone()).catch(()=>{});}).catch(()=>{}));return cached;}const fresh=await fetch(request,{cache:"no-cache"});if(isCacheableResponse(fresh))(await caches.open(AEGIS_RUNTIME_CACHE)).put(request,fresh.clone()).catch(()=>{});return fresh;})());});
